# Generate Go from proto
FROM docker.io/library/golang:1.22.1 AS buf
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.33
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3
RUN go install github.com/bufbuild/buf/cmd/buf@v1.30
WORKDIR /defs

ENTRYPOINT [ "buf" ]
CMD [ "generate" ]