# Generate Go from proto
FROM docker.io/library/golang:1.25 AS buf
RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint
WORKDIR /defs

COPY ./helloworld/*.proto .
COPY ./helloworld/*.yaml .

ENTRYPOINT [ "buf" ]
CMD [ "generate" ]
